### ISSUE TITLE
rake install failing

### ISSUE THREAD

**Issue by DimaSavitsky** [pronix/spree_webmoney#1]
Hi, I'm having troubles while installing your gem. 
Here is what I do:
1)Add 
gem "spree_webmoney", :git => "git://github.com/pronix/spree_webmoney.git"
to my Gemfile
2)run "bundle install"
3)run "rake spree_webmoney:install"

And here is the problem - this rake task (<spree_webmoney>\lib\tasks\install.rake) adresses directories ('db'  and  'public') that don't exist in the gem, so the installation fails.

Adding these directories (empty) resolves the issue, but doing it on every environment could be troublesome.

I'm using spree version 0.6, could that be the case? Am I doing something else wrong?

Anyways, thank you for your good work.

**Comment by pronix** [comment]
Hello
current version not ready for 0.60.
during 2 monthes we will upgrade it, but it is not first prioritet task, sorry.

**Comment by DimaSavitsky** [comment]
Thank you for a quick response.
